azure:
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
conda_install_tool: pixi
provider:
  linux_aarch64: default
  # linux_ppc64le: disabled due to upstream aya-build bug (target_arch_fixup doesn't normalize powerpc64le → powerpc64) - Claude Code
